services:
  #NGINX
  nginx:
    container_name: nginx
    networks:
      - main_server
    build:
      context : requirements/nginx
      dockerfile : Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
   #NODEJS
  nodejs:
    container_name: nodejs
    networks:
      - main_server
    build:
      context: requirements/nodejs
      dockerfile: Dockerfile
    volumes:
      - backend:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
  #POSTGRE
  postgres:
    container_name: postgres
    networks:
      - main_server
    build:
      context: requirements/postgre
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
#VOLUMES
volumes:
  backend:
    driver: local
    driver_opts:
      type: none
      device: '../data/backend'
      o: bind
  postgres:
    driver: local
    driver_opts:
      type: none
      device: '../data/postgre'
      o: bind
#NETWORK
networks:
  main_server:
    driver: bridge
    # nginx_server:
    #    driver: bridge
    # node_server:
    #    driver: bridge
